language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t horimz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true horimz/react-test npm run test

after_success:
  - docker build -t horimz/multi-client ./client
  - docker build -t horimz/multi-nginx ./nginx
  - docker build -t horimz/multi-server ./server
  - docker build -t horimz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push horimz/multi-client
  - docker push horimz/multi-nginx
  - docker push horimz/multi-server
  - docker push horimz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-574541530263
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
